name: talk_to_me
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter_svg: ^2.0.4
  flutter:
    sdk: flutter


dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_svg: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/backbutton.svg
    - assets/images/logo.png
    - assets/images/microsoft_icon.svg
    - assets/images/google_icon.svg
    - assets/images/apple_icon.svg


fonts:
  - family: Lora
    fonts:
      - asset: fonts/Lora-Bold.ttf
  - family: Urbanist
    fonts:
      - asset: fonts/Urbanist-Bold.ttf
      - asset: fonts/Urbanist-ExtraBold.ttf


